### ISSUE TITLE
Bug:  FileNotFoundError

### ISSUE THREAD

**Issue by grigoriosmaz** [Code-For-Groningen/temmies-cli#3]
All relevant info is in the attachment.

![WhatsApp Image 2024-11-21 at 02 53 54](https://github.com/user-attachments/assets/b3ba74d6-a8d0-46fb-a49f-9a89d7442f78)

**Comment by confestim** [comment]
fixed in [1.0.11](https://github.com/Code-For-Groningen/temmies-cli/releases/tag/1.0.11) (33373b5)

Please run `pipx upgrade temmies-cli`

**Comment by confestim** [comment]
#1 NEEDS to be solved ASAP
